# id: 1
server:
  address: ":9000"
  addressPolling: ":3334"
log:
  level: "debug"

# Health checker config
healthcheck_port: 6969
packet_limit: 8192 # 8 * 1024
protocol: "tcp"
healthcheck_message: 'te estas portando mal'
healthcheck_response: 'seras castigada'
